# Generated by Django 5.2.8 on 2025-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rollnumber', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Father', models.CharField(max_length=100)),
                ('Mother', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Bloodgroup', models.CharField(max_length=10)),
                ('DoorNo', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
